import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const  mont = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Fashion-with-ukay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${mont.variable}  ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    <head>
      <title>Fashion-with-ukay</title>
      <link rel='stylesheet' href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"/>
    </head>
      <body className="min-h-full flex flex-col">
      <Header />
      {children}
      </body>
    </html>
  );
}
